image: artifactory.wma.chs.usgs.gov/docker-official-mirror/rocker/shiny-verse:latest

stages:
  - check
  - test
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"
  RSCONNECT_URL: "$RSCONNECT_URL"
  RSCONNECT_APIKEY: "$RSCONNECT_APIKEY"

cache:
  paths:
    - $R_LIBS_USER
    
getready:
  stage: .pre
  script:
    - mkdir -p $R_LIBS_USER
    - R -e 'install.packages(c("pkgdown", "DT", "leaflet", "shiny", "shinydashboard", "RColorBrewer", "shinyAce", "shinycssloaders", "here", "tcpl", "openxlsx"), repos = Sys.getenv("CRAN_MIRROR"), lib = Sys.getenv("R_LIBS_USER"))'
    - R -e 'remotes::install_github("rstudio/connectapi")'
  cache:
    paths:
     - $R_LIBS_USER
  artifacts:
    paths:
     - $R_LIBS_USER

buildcheck:
  stage: check
  script:
    - mkdir -p $BUILD_LOGS_DIR
    - apt-get update
    - apt-get -o dir::cache::archives=${APT_CACHE} install -y --no-install-recommends qpdf pandoc pandoc-citeproc
    - R CMD build . --no-build-vignettes --no-manual
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = "error", check_dir = Sys.getenv("BUILD_LOGS_DIR"))'
  artifacts:
    paths:
      - $BUILD_LOGS_DIR

unittests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

covertests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'x <- covr::package_coverage();x;saveRDS(x, file = "cover.rds")'
  artifacts:
    paths: 
      - cover.rds
  coverage: '/Coverage: \d+.\d+\%/'

deploy:
  stage: end
  only: 
    - main
  script:
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'source("deploy_simple.R")'
  artifacts:
    paths:
      - $PKG_PATH
    expire_in: 1 week