---
title: "RPART models"
author: "S. R. Corsi"
date: "Monday, May 25, 2015"
output: ioslides_presentation
---
## Test text
This is not bold
<b> 
This is bold 
</b>

Only <b> THIS </b> is bold

<div class="red2">
This text is red
</div>


## ToxCast Regression Tree Model: Number of chemicals with hits

```{r echo=FALSE, message = FALSE, fig.show='asis',fig.width=3.5,fig.height=5}
library(rpart)
library(party)
library(partykit)

load("D:/SRCLData/R/GLRIToxCast/toxEval/mapDataAll.RData")

mainTitle <- "Passive Samplers:ToxCast"
response <- "nChem"
dat <- mapDataPassive
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 10)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))


mainTitle <- "Water Samples:ToxCast"
response <- "nChem"
dat <- mapData
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 10)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))

mainTitle <- "Water Samples:Water Quality Guidelines"
response <- "nChem"
dat <- mapDataBM
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 10)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))

```

## Comparing ToxCast to WQGs: Number of chemicals with hits

```{r echo=FALSE, message = FALSE, fig.show='asis',fig.width=4,fig.height=5}

mainTitle <- "Water Samples:ToxCast"
response <- "nChem"
dat <- mapData
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 10)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))


mainTitle <- "Water Samples:WQGs"
response <- "nChem"
dat <- mapDataBM
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 10)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))

```

## ToxCast Regression Tree Model: Maximum EAR

```{r echo=FALSE, message = FALSE, fig.show='asis',fig.width=4,fig.height=5}

mainTitle <- "Passive Samplers:ToxCast"
response <- "maxEAR"
dat <- mapDataPassive
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 32)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=10, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))


mainTitle <- "Water Samples:ToxCast"
response <- "maxEAR"
dat <- mapData
minbucket <- 6
minsplit <- minbucket*3
set.seed(seed = 32)
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))
m1 <- rpart(form,control=rpart.control(xval=5, cp=0.02, minBucket=minbucket, minsplit = minsplit),data=dat)
m2 <- prune(m1,cp=m1$cptable[which.min(m1$cptable[,"xerror"])])
if(dim(m2$cptable)[1] >1){
plot(as.party(m2), main=mainTitle, tp_args=list(id=FALSE))
} else {print("No Splits Determined")
}


```

```{r echo=FALSE, message = FALSE, fig.show='asis',fig.width=6,fig.height=6}

par(mfrow=c(2,2))
response <- "maxEAR"
form <- formula(paste(response,"~","Urban.pct + Ag.pct"))

dat <- mapData
m <- lm(form,data=dat)
plot(dat[,response],predict(m,newdata=dat))

dat <- mapDataPassive
m <- lm(form,data=dat)
plot(dat[,response],predict(m,newdata=dat))


dat <- mapDataBM
m <- lm(form,data=dat)
plot(dat[,response],predict(m,newdata=dat))

```
