---
title: "Endpoint Digdown"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{SI7}
  \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
library(knitr)
library(rmarkdown)
options(continue=" ")
options(width=60)
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 7,
                      fig.width = 7)
```

Digging down:


```{r }
library(toxEval)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringi)

path_to_tox <-  system.file("extdata", package="toxEval")
file_name <- "OWC_data_fromSup.xlsx"
full_path <- file.path(path_to_tox, file_name)

tox_list <- create_toxEval(full_path)

ACClong <- get_ACC(tox_list$chem_info$CAS)
ACClong <- remove_flags(ACClong)

cleaned_ep <- clean_endPoint_info(endPointInfo)
filtered_ep <- filter_groups(cleaned_ep)

chemicalSummary <- get_chemical_summary(tox_list, ACClong, filtered_ep)

plot_tox_boxplots(chemicalSummary, category = "Biological")

```

Now let's just look at Nuclear Receptors:

```{r fig.height=14}
CAS_NR <- unique(chemicalSummary$CAS[chemicalSummary$Bio_category == "Nuclear Receptor"])

chem_data_NR <- filter(tox_list$chem_data, CAS %in% CAS_NR)
chem_info_NR <- filter(tox_list$chem_info, CAS %in% CAS_NR)

filtered_ep <- filter_groups(cleaned_ep, groupCol = "intended_target_gene_symbol")

chemicalSummary <- get_chemical_summary(tox_list,ACClong, filtered_ep,
                                        chem.data = chem_data_NR,
                                        chem.info = chem_info_NR)

plot_tox_boxplots(chemicalSummary, category = "Biological")

```

And now...we dig down to just "PTEN":

```{r}

CAS_PTEN <- unique(chemicalSummary$CAS[chemicalSummary$Bio_category == "PTEN"])

chem_data_PTEN <- filter(chem_data_NR, CAS %in% CAS_PTEN)
chem_info_PTEN <- filter(chem_info_NR, CAS %in% CAS_PTEN)

chemicalSummary <- get_chemical_summary(tox_list, ACClong, filtered_ep, 
                                        chem.data = chem_data_PTEN, 
                                        chem.info = chem_info_PTEN)
plot_tox_endpoints(chemicalSummary)

```



