---
title: "Introduction to toxEval"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: false
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction to toxEval}
  \usepackage[utf8]{inputenc}
---


The `toxEval` R-package includes a set of functions to analyze, visualize, and organize measured concentration data as it relates to ToxCast data. These functions allow great flexibly for exploring the potential biological affects of measured chemicals. Also included in the package is a browser-based application made from the `shiny` R-package. There is less customization from the application, but it is a convenient way to explore the data. 

This vignette describes the process to prepare the data and use the shiny application. There is also a section on installing and updating the package, since it is not on CRAN. 

# Introduction

The U.S. EPA's Toxicity Forecaster <a href="https://www.epa.gov/chemical-research/toxicity-forecasting" target="_blank">ToxCast</a> is a database with thousands of chemicals that can give biological relevance to measured concentrations. The `toxEval` package attempts to simplify the workflow for exploring data as it relates to the benchmark data. By default, the workflow uses the ToxCast information, but there is also a way to provide alternative benchmarks. This could be useful for comparing ToxCast results with other toxicity benchmark databases.

When using the ToxCast endPoints for analysis, it will be important to have at least a minimal understanding of what ToxCast data is, and which ToxCast data is relevant to your study. There are many useful resources <a href="https://www.epa.gov/chemical-research/toxicity-forecasting" target="_blank">here</a>. There is also a tool called the <a href="https://actor.epa.gov/dashboard/" target="_blank">TosCast Dashboard</a> that has a wealth of information on ToxCast data.

So what are we doing? First, we calculate an Exposure-Activity Ratio (EAR) for each measurement. Then we can explore the EARs based on a wide variety of groupings to explore the data.

## Exposure-Activity Ratio

A Exposure-Activity Ratio (EAR) is the measured concentration divided by a concentration that was determined to cause some activity. The ToxCast database (as provided in the current version of `toxEval`) provides 991 "endPoints" for more than 6575 chemicals. Each endPoint is a single test that was done to detect some form of activity. 

In order to get consistent EAR results, it is important to use the correct units. The `toxEval` package assumes all measured concentration is repored in micrograms per liter (ug/L). ToxCast data is reported in log(uM), so the `toxEval` package automatically performs the unit conversion.

ToxCast uses high-throughput assays to create does-response curves for each of these chemical/endPoint combinations. Activity concentration at cutoff (ACC) values of these does response curves are provided in the `toxEval` package. ACC was choosen over the chemical-specific half-maximal activity concentration (AC50) as described in <a href="https://doi.org/10.1021/acs.est.7b01613" target="_blank">Blackwell 2017</a>.

## What is an "endPoint"?

An endPoint is "associated with the perturbation of specific biological processes identified for the confirmation or monitoring of predicted site-specific hazards" <a href="https://doi.org/10.1021/acs.est.7b01613" target="_blank">Blackwell 2017</a>. That means a very specific action was tested, and concentration at which that activity was observed was determined. For ToxCast endPoints, that is via the ACC value in a dose response curve.

## Grouping options

Often, a single endPoint is too specific to be of much interest. ToxCast has provided tables that group individual endPoints into more generalized categories. The grouping summary table is included in `toxEval` and can be explored via the `endPointInfo` data:

```{r endPointInfo, eval=FALSE}
library(toxEval)
endPointInfo <- endPointInfo
```

See the help file `?endPointInfo` for specifics on how the table was downloaded.

Throughout the `toxEval` analysis, there are graphing and table functions that will summarize EARs based on either "Biological" groupings (as defined by a group of endPoints) or "Chemical Class" groupings (as defined by a group of chemicals).

The default grouping of ToxCast endPoints is "intended_target_family", but depending on the analysis, it may be more appropriate to use other grouping categories. 
