---
title: "SI 2: Detection Levels"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{SI2}
  \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
library(knitr)
library(rmarkdown)
options(continue=" ")
options(width=60)
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.height = 7,
                      fig.width = 7)
```

Using the detection levels as concentrations:


```{r }
library(readxl)
library(toxEval)
library(dplyr)
library(tidyr)
library(ggplot2)

path_to_tox <-  system.file("extdata", package="toxEval")
file_name <- "OWC_data_fromSup.xlsx"
full_path <- file.path(path_to_tox, file_name)

chem_data <- read_excel(full_path, sheet = "Data")
chem_info <- read_excel(full_path, sheet = "Chemicals") 
chem_site <- read_excel(full_path, sheet = "Sites")
exclusion <- read_excel(full_path, sheet = "Exclude")

#Trim names for graph:
chem_info$Class[chem_info$Class == "Antimicrobial Disinfectants"] <- "Antimicrobial"
chem_info$Class[chem_info$Class == "Detergent Metabolites"] <- "Detergent"
chem_info$Class[chem_info$Class == "Flavors and Fragrances"] <- "Flavor/Fragrance"

ACClong <- get_ACC(chem_info$CAS)
ACClong <- remove_flags(ACClong)

cleaned_ep <- clean_endPoint_info(endPointInfo)
filtered_ep <- filter_groups(cleaned_ep)

# Substitute max LDL or MDL for actual values:

chem_data <- chem_data %>%
  left_join(select(chem_info,
                   CAS,
                   MDL = `Maximum method detection level`,
                   LDL = `Maximum laboratory reporting level`),
            by="CAS") %>%
  rowwise() %>%
  mutate(Value_new = max(MDL, LDL))

chemicalSummary <- get_chemical_summary(ACClong,
                                        filtered_ep, 
                                        chem.data = chem_data, 
                                        chem.site = chem_site, 
                                        chem.info = chem_info,
                                        exclusion = exclusion)

plot_DL <- plot_tox_boxplots(chemicalSummary, "Chemical")

plot_DL

```