on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    env: NOT_CRAN: "true"
    steps:
      - uses: actions/checkout@c0a81a463886bb75afe234e07a9fd5bb79219196

      - uses: r-lib/actions/setup-r@12d8dd416fec5aaa60f2f54609b713b2ec031a94

      - uses: r-lib/actions/setup-pandoc@e0a5ffdf0b121aa1c2112f65e54b642a81dc29d9

      - uses: r-lib/actions/setup-r-dependencies@813ef1cb62cf0b4b51a044419024c37807fa8095
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
